//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBStoreSport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockHistory
    {
        public int StockID { get; set; }
        public int ProductID { get; set; }
        public int QuantityChange { get; set; }
        public string ActionType { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string AdminUser { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
